### ISSUE TITLE
Using ParseFS and embed.FS

### ISSUE THREAD

**Issue by aranw** [yuriizinets/kyoto#47]
I've been trying to figure out a pattern to use `embed.FS` and `template.ParseFS` for delivering the HTML files 

Do you have any examples for this? I've been struggling with a couple of different errors and including the Funcs with the parsed templates

```template: \"templates/pages.home.html\" is an incomplete or empty template```

```
	//go:embed templates
	Templates embed.FS
```

```
	return template.Must(
		template.New("templates/pages.home.html").Funcs(kyoto.TFuncMap()).ParseFS(assets.Templates, "templates/pages.home.html"),
	)
```

**Comment by aranw** [comment]
I tried the suggested changes and I'm still receiving the same error 

```
template: \"templates/pages.home.html\" is an incomplete or empty template
```
and when I remove the `Funcs(kyoto.TFuncMap())` call I get the following error

```
error":"template: pages.home.html:14: function \"dynamics\" not defined
```

If I go ahead and remove the ` {{ dynamics }}` 

I go back to having that incomplete or empty template error again

**Comment by yuriizinets** [comment]
Awesome! Glad to see that it's working for you.  
I'm closing this issue. In case of any issues feel free to open new issue, write to general chat or write to me directly.
